### ISSUE TITLE
Class 'PhpAmqpLib\Connection\AMQPStreamConnection' not found

### ISSUE THREAD

**Issue by balajeed** [romainrg/codeigniter-rabbitmq-library#1]
i followed the complete steps which you had mentioned. but i am getting the error as below... Same works fine when i run as a standalone php file as mentioned at http://www.rabbitmq.com/tutorials/tutorial-one-php.html

Severity: Error
Message: Class 'PhpAmqpLib\Connection\AMQPStreamConnection' not found
Filename: libraries/Rabbit_mq.php
Line Number: 46

**Comment by romainrg** [comment]
Hi mate,

I think this is a composer issue.
You have to change the path of your AMQPStreamConnection installation.

Tell me if you have another issue.

Romain G.

2016-03-05 5:45 GMT+01:00 Balajee notifications@github.com:
