### ISSUE TITLE
where to add /vendor/autoload.php' file

### ISSUE THREAD

**Issue by balajeed** [romainrg/codeigniter-rabbitmq-library#2]
Hi,

i am not sure whether you had internally added this line into your code require_once **DIR**.'/vendor/autoload.php' if not, please let us know where to include this? Do we need to add this in our controller? 
- Balajee.

**Comment by romainrg** [comment]
Hi mate,

You have to change the path of your AMQPStreamConnection installation.
For me, it's in the vendor folder.

Tell me if you have another issue.

**Comment by balajeed** [comment]
Even for me its an vendor folder but wondering whether i need to manually add the autoload somewhere in the code ... because i am keep getting the message as "Class 'PhpAmqpLib\Connection\AMQPStreamConnection' not found" and i tried my best and unable to fix it. Could you please help me on this and let me know why i am getting the error ... Attached the vendor folder structure and not sure what i am missing here. 
<img width="331" alt="screen shot 2016-03-08 at 3 53 31 pm" src="https://cloud.githubusercontent.com/assets/7553377/13598828/ff4a6f66-e545-11e5-97dd-6168a0af43c2.png">

same works fine when i create a static rabbitmq_sender.php file in my project root as below. 
`<?php 
require_once **DIR** . '/vendor/autoload.php';
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;
$connection = new AMQPStreamConnection('localhost', 5672, 'guest', 'guest');
$channel = $connection->channel();
$channel->queue_declare('test', false, false, false, false);

$msg = new AMQPMessage('Hello World!');
$channel->basic_publish($msg, '', 'test');

echo " [x] Sent 'Hello World!'\n";
$channel->close();
$connection->close();
?>`

**Comment by romainrg** [comment]
Can I see the complete structure of your project ?
